# Generated by Django 5.2.3 on 2025-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads'),
        ),
    ]
